# Generated by Django 2.1.2 on 2019-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default='sposób przygotowania'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
